### ISSUE TITLE
Erstes Issue von Kirsten Anders (kiraGit67)

### ISSUE THREAD

**Issue by kiraGit67** [danielkull/unser-test-project#4]
Aufgabenliste

- [ ] Nimm die Einladung desjenigen an, der das Projekt erstellt und zur Zusammenarbeit daran eingeladen hat
- [ ] Klone Dir das Repository auf Deinen lokalen Rechner
- [ ] Installiere die Dependencies durch npm install
- [ ] Erstelle ein erstes Issue

**Comment by kerstin-m** [comment]
Noch ein Test
